### ISSUE TITLE
Why AsyncRoute was removed?

### ISSUE THREAD

**Issue by darxx** [angular/vladivostok#101]
Notice that **AsyncRoute**  is no longer present.
How to load components and routes on demand is **AsyncRoute** removed?
Can`t find. I need to integrate angular components as plugins from another sources. Is it another why to make routes and components loaded from external source that is on the same domain as plugins?

@angular/router - **v3.0.0-alpha.7** 
Something like https://www.sitepoint.com/community/t/dynamic-route-and-controller-from-json/212806

**Comment by brandonroberts** [comment]
The routes were simplified so there is on one type of `Route` now. You can still load components async right now and async routes will be coming soon.

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9472
