### ISSUE TITLE
Bug: Can't generate link including secondary route with routerLink

### ISSUE THREAD

**Issue by brandonroberts** [angular/vladivostok#11]
I can navigateByUrl to a primary and secondary route, but using a routerLink to link to a primary and secondary route isn't supported.

Plunker: http://plnkr.co/edit/fo0lMsuimryTqeQxkiHW?p=preview

**Comment by gustavLatte** [comment]
I had the same issue and solved it by defining the router config as follows:
` <a [routerLink]="['../aux:training/5']">chat 5</a>`
(no need for the parentheses)

you can see the complete code here: [here](https://github.com/gustavLatte/NG2Router3/blob/master/src/app/location-trainings/location-trainings.component.html)

@gmoothart - hope it works for you
