### ISSUE TITLE
Bug: URL is not updated to index route path

### ISSUE THREAD

**Issue by brandonroberts** [angular/vladivostok#16]
If an index route is set, the route is rendered, but the `path` is not reflected in the URL.

Plunker: http://plnkr.co/edit/LbpkBQ?p=preview

**Comment by sspilleman** [comment]
Have this too on "@angular/router": "3.0.0-alpha.3"

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/vladivostok/commit/e82f20afbe502d911e6b36ba401763ccb6c4c239
