### ISSUE TITLE
Bug: Router doesn't render / route unless defined as index route

### ISSUE THREAD

**Issue by brandonroberts** [angular/vladivostok#21]
If I don't define an index route, the route path that matches the current location should still work. I should only need to define an index route if I a route path other than `/` to be rendered when visiting the `/` path.

http://plnkr.co/edit/6ROIfl?p=preview

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/vladivostok/commit/e82f20afbe502d911e6b36ba401763ccb6c4c239
