### ISSUE TITLE
Feat: Add support for Pathless Routes

### ISSUE THREAD

**Issue by otodockal** [angular/vladivostok#23]
It would be great to support **Pathless Routes** like **@ngrx/router** does.
https://github.com/ngrx/router/blob/master/docs/overview/route.md#pathless-routes

If it's planned(or something similar) or even implemented, sorry for the SPAM.

**@ngrx/router** example/usecase:
http://plnkr.co/edit/X2tKoD?p=preview

**vladivostok** example (doesn't work...):
https://plnkr.co/edit/GFcgFz?p=preview

**Comment by SergeySolonko** [comment]
Agree, It would be cool if it would be possible to use route config like this:
```
{
    path: '/',
    component: ProtectedComponent,
    index: true,
    children: [
      {path: '/dashboard', component: DashboardComponent, index: true}
    ]
  }
```

So path will be ```/dashboard```

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9474
