### ISSUE TITLE
Bug: CanDeactivate doesn't run from child route

### ISSUE THREAD

**Issue by brandonroberts** [angular/vladivostok#26]
http://plnkr.co/edit/ld1HSyda4uhP6LYKYawO?p=preview

1. Click on the "Away" link
2. Click on the "Home" link
3. Note the browser confirm dialog, Click "OK"
4. Click on the "Level 1 Home" link
5. Click on the "Go Home" button or the "Away" link
6. Note that no browser confirm dialog was displayed

The "Away" route and the "Level 1 Home" route have the same guard in the configuration.

**Comment by laco0416** [comment]
this bug breaks something like _sidebar_. 

e.g.:  navigating from `/menu1/item1` to `/menu2/item1` 

```
TypeError: Cannot read property '_routeConfig' of null at GuardChecks.runCanDeactivate
```

**Comment by vsavkin** [comment]
I think this was fixed some time ago. Added a test to make sure it works https://github.com/angular/vladivostok/commit/916edb21b4e716bd62b5c8fd639a394fd8718f60
