### ISSUE TITLE
Proposal: Assume relative navigation are being performed relative to the current activated route

### ISSUE THREAD

**Issue by nosachamos** [angular/vladivostok#32]
When performing relative navigation involving routes that start with `./` and `../`, could we make the `{relativeTo: this.currentActivatedRoute}` implicit?

Example, make:
```
// from within /team/3, perform a relative navigation to /team/3/details
this.router.navigate(['./details'], {relativeTo: this.route});
```

...be equivalent to:

```
// from within /team/3, perform a relative navigation to /team/3/details
this.router.navigate('./details');
```

Another example, make:

```
// from within /team/3, perform a relative navigation to /team/4
this.router.navigate(['../4'], {relativeTo: this.route});
```

...be equivalent to:

```
// from within /team/3, perform a relative navigation to /team/4
this.router.navigate('../4');
```

Not sure this is feasible, but I suppose performing navigation relative to the currently activated route will be the majority of the cases... this way we could save folks the trouble to inject the current ActivatedRoute, etc.

Thoughts?

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9476
