### ISSUE TITLE
Bug: redirectTo doesn't work with '/'

### ISSUE THREAD

**Issue by orangesoup** [angular/vladivostok#33]
`redirectTo` should redirect from `/` as well.

```
{ path: '/', redirectTo: '/some/random/route' }
```

When `/` opened the location/url stays at `/` instead of redirecting to `/some/random/route`, basically nothing happens.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/vladivostok/commit/e82f20afbe502d911e6b36ba401763ccb6c4c239
