### ISSUE TITLE
Can't install: typings error

### ISSUE THREAD

**Issue by deastr** [angular/vladivostok#34]
I use Visual Studio.NET 2015 and currently using Angular 2 in an ASP.NET MVC project. I've added the following line to my projects package.json config:

>..
"@angular/router": "3.0.0-alpha.3",
..

and it started installing but failed giving this error:

>PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\npm.CMD" install
npm WARN install Couldn't install optional dependency: Unsupported
-> @angular/router@3.0.0-alpha.3 postinstall D:\Projects\MyProject\Source\Management\Management.Web.UI\node_modules\@angular\router
-> typings install
typings ERR! message Unable to resolve Typings dependencies
typings ERR! caused by Unable to find "typings.json" from "D:\Projects\MyProject\Source\Management\Management.Web.UI\node_modules\@angular\router"
typings ERR! cwd D:\Projects\MyProject\Source\Management\Management.Web.UI\node_modules\@angular\router
typings ERR! system Windows_NT 6.3.9600
typings ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Users\\armagan.ergon\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v5.4.1
typings ERR! typings -v 0.8.1
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
npm WARN EPEERINVALID angular2@2.0.0-beta.17 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! @angular/router@3.0.0-alpha.3 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @angular/router@3.0.0-alpha.3 postinstall script 'typings install'.
npm ERR! This is most likely a problem with the @angular/router package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get their info via:
npm ERR!     npm owner ls @angular/router
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\MyProject\Source\Management\Management.Web.UI\npm-debug.log

I'm attaching package.json and npm-debug.log file.

What should I do? 

[package.json.txt](https://github.com/angular/vladivostok/files/308974/package.json.txt)
[npm-debug.log.txt](https://github.com/angular/vladivostok/files/308850/npm-debug.log.txt)

**Comment by brandonroberts** [comment]
You need the latest version of typings `"typings": "^1.0.4",`

**Comment by deastr** [comment]
@brandonroberts: Sorry I forgot to add that typings is already globally installed. Running "typings -v" in Node.js cmdline gives "0.8.1" result.

I've added "" to the package.json and installed typings anyway and now I'm getting this error while trying to install the router:

>PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\npm.CMD" install
npm WARN install Couldn't install optional dependency: Unsupported
> @angular/router@3.0.0-alpha.3 postinstall D:\Projects\MyProject\Source\Management\Management.Web.UI\node_modules\@angular\router
> typings install
typings WARN enoent Path "D:\Projects\MyProject\Source\Management\Management.Web.UI\node_modules\@angular\router\typings.json" is missing
└── (No dependencies)
ASP.NET@1.0.0 D:\Projects\MyProject\Source\Management\Management.Web.UI
├── @angular/router@3.0.0-alpha.3 
└── UNMET PEER DEPENDENCY reflect-metadata@0.1.3
npm WARN EPEERINVALID angular2@2.0.0-beta.17 requires a peer of reflect-metadata@0.1.2 but none was installed.

There is a node_modules\@angular folder but not a node_modules\@angular\router.

**Comment by brandonroberts** [comment]
Are you on the @angular RC or still on a beta version?

**Comment by deastr** [comment]
I'm using 2.0.0-rc.1

**Comment by brandonroberts** [comment]
Try installing the router by itself and see what you get. `npm install @angular/router@3.0.0-alpha.3`. Its fine you get warnings about unmet dependencies

**Comment by deastr** [comment]
@brandonroberts : tried that, same "typings.json is missing" error..

**Comment by deastr** [comment]
Scratch that. Turns out that "typings.json is missing" is just a warning and it _does_ install router. 

Thanks.

**Comment by brandonroberts** [comment]
Great
