### ISSUE TITLE
Properly model querystring input which can contain multiple values

### ISSUE THREAD

**Issue by xealot** [angular/vladivostok#35]
Note: This is a copy of my issue from, https://github.com/angular/angular/issues/9138.

I don't know which is the appropriate location.

**I'm submitting a ...**
- [x] bug report
- [x] feature request

**Current behavior**

In the old router, the new router and the very new router querystring parameters always are accessible as `{[k:string]:string}`. To pass an array of values via the querystring we have to rely on encoding within the application to serialize and then deserialize the array. We *should* be able to simply rely on existing URL standard behavior.

Adding to my frustration, there is already a class, `URLSearchParams` that fully models the querystring but seems unused when retrieving url search params from the router.
https://angular.io/docs/ts/latest/api/http/URLSearchParams-class.html

**Expected/desired behavior**

When retrieving data parsed from a querystring it should be presented either in a datastructure that supports the standard or in a class that models it properly.

```typescript
const q: Observable<URLSearchParams> = r.routerState.queryParams;
```

```typescript
const q: Observable<{[k:string]:string[]}> = r.routerState.queryParams;
```

My vote is for the URLSearchParams version of course.

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9477
