### ISSUE TITLE
[bug] trying to resolve the root cmp when using lazy loading

### ISSUE THREAD

**Issue by vicb** [angular/vladivostok#37]
When integrated in periscope & using lazy loading in a compiled app (periscope) the router tries to resolve the root component class.

Seems like the return value is not even used (return `Promise.resolve(null)` works).

Other than that, routing works great w/ lazy loading + compile app. Great work @vsavkin !

**Comment by ocombe** [comment]
Can you share the route definition when using a lazy loaded component? It looks like the "loader" property from previous versions of the router is gone?

**Comment by DzmitryShylovich** [comment]
example with lazy loading https://plnkr.co/edit/g8FGMbxECKtj9j1pdLSw?p=preview
