### ISSUE TITLE
Router should be built on current stable release of TypeScript

### ISSUE THREAD

**Issue by jeffschwartz** [angular/vladivostok#40]
The router's reliance on edge typescript features and non production releases of typescript is bad and prevents many of us from becoming early adopters of the router. Please back-track and support TypeScript v1.8.10.

**Comment by alvipeo** [comment]
I actually used the same version of Typescript as in router in my project and it works. That's least important issue I guess (but I found others)

**Comment by jeffschwartz** [comment]
@alvipeo I'd actually be shocked if it didn't but when it comes to angular and routers then perhaps I shouldn't be :(

**Comment by jeffschwartz** [comment]
I'm closing this out because of #39. Thank you @vsavkin.
