### ISSUE TITLE
Wildcard-based or parameter-based routes should update the current state

### ISSUE THREAD

**Issue by ebrehault** [angular/vladivostok#41]
Maybe I am missing something, but apparently, the router changes the app state only if the requested URL matches a different route than the current one.
That's ok with static routes, but with a wildcard route, the same route can match several URLs so the state must be updated even if we navigate to an URL matching the same route.

Currently, if we declare the following route:
```
{ path: '/:*', component: Page }
```
then navigating from `/page1` to `/page2` will let the app in the same state and the page is not refreshed.

Here is an example: http://plnkr.co/edit/G7wcTcKnGAXpFXrIfBxO?p=preview

I have just noticed we get the same problem if we use positional parameters:
```
{ path: '/:id', component: Page }
```

**Comment by vsavkin** [comment]
fixed here:
https://github.com/angular/vladivostok/commit/e82f20afbe502d911e6b36ba401763ccb6c4c239

add a test verifying that it works here: https://github.com/angular/vladivostok/commit/32d4204bca547ef39d4bdd2ec5f6bd5f4710f253
