### ISSUE TITLE
Support adding additional data to Route-Configurations (fka. RouteData)

### ISSUE THREAD

**Issue by choeller** [angular/vladivostok#43]
With the deprecated Router it was possible to add additional data to a Route-Configuration like this:

```
@RouteConfig([
  {path: '/about', component: AboutComponent, name: 'About', data: {title :"About us"}},
])
```
with this information it was possible to do some generic operations when activating the route (e.g. setting the page title via `Title`-Service. It would be cool to have this possiblitity again.

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9478
