### ISSUE TITLE
Defining an aux-route in child-component prevents leaving this route again

### ISSUE THREAD

**Issue by choeller** [angular/vladivostok#44]
When having 2 router-outlets in a child-component the aux-functionality works well, but as soon as you want to leave the child-route the following exception is thrown and the router stops working:
```
EXCEPTION: Error: Uncaught (in promise): Error: Outlet is not activated
```
the following plnkr demonstrates the behaviour:

http://plnkr.co/edit/wnHZzoB4xj5BbKWNzXUK?p=preview

the aux-outlet is defined in `crisis-center.component.ts`. When the application starts the crisis outlet is entered, when now trying to change to the heroes page the error occurs.

My use-case is to have an encapsulated part of my application that deals with "Tasks". When selecting a task I want to open a sidebar and display some important information about the task (JIRA-like). I already got this working in my application, but when once entering the "tasks" part I can never leave it again.

**Comment by gfrSE** [comment]
sorry to misuse your issue, but could you tell me how to navigate to aux-routes via [routeLink] ?
( if its possible? )

**Comment by choeller** [comment]
@gfrSE According to https://github.com/angular/vladivostok/issues/11 you can simply do something like:
```html
<a [routerLink]="['../aux:training/5']">chat 5</a>
```

**Comment by michaelchiche** [comment]
@choeller this seems to "half" work.  
What I mean is that the link is correctly generated and when clicked, it does load the secondary route, but it does not update the URL...

**Comment by gfrSE** [comment]
@michaelchiche it does.
See this Plunker: http://plnkr.co/edit/pI95yAXxukcvUfz5vMiK?p=preview

The additional link **AUX-Route** on the _Crisis Center_-View

**Comment by michaelchiche** [comment]
I seem to have a weird bug. My routerlink directive does not insert the right data for ng-reflect-href & href attributes.

<img width="693" alt="capture d ecran 2016-06-21 a 11 20 05" src="https://cloud.githubusercontent.com/assets/371278/16224399/33bc1700-37a2-11e6-9e67-984699fab5d1.png">

I will make a plunker  to try to show/reproduce this problem.

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9479
