### ISSUE TITLE
Create `@angular/router/testing` and `ROUTER_FAKE_PROVIDERS`

### ISSUE THREAD

**Issue by delasteve** [angular/vladivostok#45]
In order to test a component with a view that contains `[routerLink]`'s, you currently have to do the following:

```
class MockRouter { }
class MockActivatedRoute { }

...

beforeEachProviders(() => [
  provide(Router, { useClass: MockRouter }),
  provide(ActivatedRoute, { useClass: MockActivatedRoute })
]);
```

The v2 router has `ROUTER_FAKE_PROVIDERS`. It would be nice to have this again.

**Comment by antonybudianto** [comment]
really need this back

**Comment by JohannesHoppe** [comment]
Yes! This is a must have!

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9496
