### ISSUE TITLE
Feature: Support Route-Aliases

### ISSUE THREAD

**Issue by Sabartius** [angular/vladivostok#47]
Router-Deprecated had a very nice feature for route-aliases/named routes, which allowed to simplify the routing, especially in larger applications.

```
@RouteConfig([
  {path: '/crisis/about', component: AboutCrisisComponent, as: 'About'},
])
```

**Comment by nosachamos** [comment]
@Sabartius the RC router already dropped route names, and AFAIK this won't be implemented in this router either.

This one can probably be closed.

**Comment by vsavkin** [comment]
Since using route names creates a lot of problems for lazy loading and complicated the mental model, we dropped it.

**Comment by Sabartius** [comment]
Too bad, my app heavily relies on named routes, because route-names are determined by the backend.
Looks like i need a new approach :(

**Comment by zoechi** [comment]
I guess you can create constants named like your routes with the path as value, then you get appx the same result.
