### ISSUE TITLE
The router ver 3.0.0-alpha.3 doesn't found children routes

### ISSUE THREAD

**Issue by Koronos** [angular/vladivostok#52]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
If you have a routing like this:

    import { CrisisDetailComponent } from './crisis-detail.component';
    import { CrisisListComponent }   from './crisis-list.component';
    import { CrisisCenterComponent } from './crisis-center.component';
    import { CrisisDetailGuard }     from './crisis-detail.guard';
    
     export const CrisisCenterRoutes = [
       {
         path: '/',
         component: CrisisCenterComponent,
         index:true,
         children: [
            { path: '/', component: CrisisListComponent, index: true },
            { path: '/:id', component: CrisisDetailComponent, canDeactivate: [CrisisDetailGuard] }
        ]
       }
    ];

When you enter to `"/"`, you can enter correctly to the component `CrisisListComponent`, but if you try to enter to `"/1"` for example, the route cannot be found.

Hoverer, if you remove the `index: true` from the path `"/"` in the children array. You can't see the CrisisListComponent in the router-outlet.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
The file that have the problem is app/crisis-center/crisis-center.routes.ts

http://plnkr.co/edit/65PD2y1DFm7eCtRSdwZK?p=preview

* **What is the expected behavior?**

That you can enter to all children routers without problem.

* **Please tell us about your environment:**
The project is compiled under webpack, and in the example in plunker, is under sys
* **Angular version:** 2.0.0-RC.1 
 
* **Browser:** [all | Opera 38.0.2220.29] 
 
* **Language:** [TypeScript 1.8.10 | ES5 ]

**Comment by brandonroberts** [comment]
The index routes have been deprecated in the latest alpha(6) in favor of redirects.

**Comment by Koronos** [comment]
When you right, you right, now the router is broken for the RC2 update..., ok issue close.
