### ISSUE TITLE
alpha3 router requires parenthesis in query string to be encoded

### ISSUE THREAD

**Issue by kamarouski** [angular/vladivostok#58]
The router currently requires parenthesis characters '(' and ')' to be encoded in query string. Otherwise it replaces query string parameter with 'true'  value

e.g. http://aweso.me/path?p=(param) is replaced with http://aweso.me/path?p=true

http://aweso.me/path?p=%28param%29 works fine

Parenthesis are valid query string characters, it's not encoded by encodeURIComponent.

Expected result: parenthesis characters are supported without encoding.

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9482
