### ISSUE TITLE
Slash in route params values Cannot match any routes on refresh with HashLocationStrategy

### ISSUE THREAD

**Issue by Delagen** [angular/vladivostok#59]
simple url http://site.com/#/route;back=/a/b/c

Error: Cannot match any routes: 'route;back=true/a/b/c'

**Comment by Delagen** [comment]
Referece angular/angular#8603 angular/angular#8461

**Comment by zoechi** [comment]
What's the purpose of this issue if there are 2 similar already? What router version are you using?
If your previous comment was meant to point out duplicates you could close the issue yourself.

**Comment by Delagen** [comment]
3.0.0-alpha.6
Third iteration of router but still not usable in some cases, and solution not provided

**Comment by zoechi** [comment]
Sorry, I missed that this is not the https://github.com/angular/angular repo

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9483
