### ISSUE TITLE
Bug: Router doesn't render `/` route

### ISSUE THREAD

**Issue by brandonroberts** [angular/vladivostok#6]
**Current behavior**

When the `/` route is loaded, the `Home` component is not rendered

**Expected/desired behavior**

When the `/` route is loaded, the `Home` component is rendered

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/0Qv95J?p=preview

If you click on the `Away` link, the route component is rendered correctly, but if you click on the `Home` link, nothing is displayed, then the `Away` link stops working also.

cc: @vsavkin

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9485
