### ISSUE TITLE
route not found if "index: true"

### ISSUE THREAD

**Issue by gfrSE** [angular/vladivostok#60]
Routes are not found if the index-flag is set to true.
Without this flag set in any of my routes it works like expected.

Using Alpha.6

**Comment by gfrSE** [comment]
If there are child routes, same result: route not found.

**Comment by brandonroberts** [comment]
The index flag has been deprecated. Use a redirectTo instead to set a default.

```js
const routes = [
  { path: '/', redirectTo: '/somewhere', terminal: true },
  { path: '/somewhere', component: SomeComponent }
]
```

**Comment by gfrSE** [comment]
Sorry, didn't know that.. Where could I read this?

And what about this terminal flag? :)

Thanks!

**Comment by brandonroberts** [comment]
It will be in the new developer guide. The `terminal` flag is mainly for redirects and give you more control over path matching. It basically tells the router to stop matching any further once the path is found.

**Comment by gfrSE** [comment]
directly browsing to: `http://localhost/fb01` or using a link like `[routerLink]="['fb01']"`

.. works with:

````
export const Fb01Routes = [
  { path: '/', redirectTo: '/fb01', terminal: true },
  {
    path: '/fb01',
    component: Fb01Component,
    children: [
      { path: '/', component: NewComponent },
      { path: '/add', component: NewComponent },
      { path: '/overview', component: OverviewComponent },
    ]
  }
];
```

.. but won't work with:
```
export const Fb01Routes = [
  { path: '/', redirectTo: '/fb01', terminal: true },
  {
    path: '/fb01',
    component: Fb01Component,
    children: [
      { path: '/add', component: NewComponent },
      { path: '/', redirectTo: '/add', terminal: true },
      { path: '/overview', component: OverviewComponent },
    ]
  }
];
```

browsing directly to `http://localhost/fb01/add` works with both of them..

**Comment by gfrSE** [comment]
seems like the `redirectTo` path needs to be absolute in child routes?!

```
export const Fb01Routes = [
  { path: '/', redirectTo: '/fb01', terminal: true },
  {
    path: '/fb01',
    component: Fb01Component,
    children: [
      { path: '/add', component: NewComponent },
      { path: '/', redirectTo: '/fb01/add', terminal: true },
      { path: '/overview', component: OverviewComponent },
    ]
  }
];
```
works..

**Comment by brandonroberts** [comment]
The `redirectTo` with a leading `/` is considered to be global/absolute. In the child route, try a `redirectTo: 'add'` so its relative to where you are.

**Comment by gfrSE** [comment]
damn, you are so right!

**Comment by brandonroberts** [comment]
@gfrSE you can close it
