### ISSUE TITLE
CanActivate.canActivate appears not to trigger

### ISSUE THREAD

**Issue by robert-bor** [angular/vladivostok#63]
First off, thank you guys for the great work you are doing. I really appreciate your brilliant work. Please, keep it up! :)

Just playing around with the new v3 router. It appears that the canActivate method does not trigger. The class implements the interface CanActivate. Within the class, the canActivate method just prints a line to see if it triggers. 

Here is the code:
```
import { Component } from '@angular/core';
import { AlertComponent, DATEPICKER_DIRECTIVES } from 'ng2-bootstrap/ng2-bootstrap';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { Observable } from 'rxjs';

@Component({
  selector: 'about',
  template: require('./about.html'),
  directives: [AlertComponent, DATEPICKER_DIRECTIVES]
})

export class About implements CanActivate {
  date: Date = new Date();

  constructor() {
    console.log('> constructor hit');
  }
  
  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | boolean {
    console.log('> canActivate hit');
    return true;
  }

}
```

The route activates as it should and the constructor console.log triggers as well. The console.log in `canActivate` never triggers.

What I am trying to accomplish (once past this issue) is similar to what `resolve` once did in ui-router. In this case, it should be able to finish loading data from the server before rendering the view.

Am I doing something wrong or is this not yet implemented?

**Comment by brandonroberts** [comment]
CanActivate is not defined in the component. You implement the CanActivate interface in a separate class and add the guard to your route config

See plunker: http://plnkr.co/edit/gQcyGu?p=preview

**Comment by robert-bor** [comment]
Thanks for your answer, Brandon.

I've got your example working in my code as well.

It is possible to add the component that you require the guard on as a canActivate array parameter. However, this requires you to bootstrap the guard (which is the component itself) as well. However, it will also create two instances (constructor is called twice).

**Why has the choice been made not to allow the component itself to supply its own canActivate parameter?** Doing so would ease the passing of data to the view component (ie, itself).

**Comment by nosachamos** [comment]
The reason for that is that if you don't want a particular route to be
activated, you probably also want to prevent the component to be
constructed. The guard is supposed to be a thin layer, just a simple class
so you get DI support. Instantiating that for a route that doesn't activate
is OK, and you only get the component instantiated if the route is then
allowed to activate. For this reason, you should put your guard in a
separate class, and not in the component.

2016-06-16 13:46 GMT-05:00 Robert Bor <notifications@github.com>:

**Comment by brandonroberts** [comment]
The biggest reason is that we don't want to create an instance of the component to make sure we can use and render the component. That's why the guard is separate from the component. Imagine if you have guards across multiple levels and one fails,  you don't want to render half the routes only to have back them out because one of the checks failed.

What data are you trying to share between the guard and the component? You can accomplish this using a service.

**Comment by robert-bor** [comment]
Ok, so the canActivate is basically intended as a defense against premature creation of components. 

> What data are you trying to share between the guard and the component? You can accomplish this using a service.

The same as ui-router's resolve. Suppose a component would render, for example, the details of a product. I then use the guard (or resolver) to load the product details. As soon as this is done, the component is created and notified of all resolved content.

The reason I want to do it this way is to prevent having to create logic to deal with a product not yet loaded. Having a system in a predictable state makes it less error-prone and easier to reason about. 

I'm interested to hear how you would address this issue.

**Comment by brandonroberts** [comment]
The "resolve" functionality is a planned feature but not implemented yet. You could use a guard to pre-fetch some data and store it using a shared service, or put it in a ngrx/store and return true to continue routing. Then in your route you access the service/store to retrieve that data. Still works the same, although your not specifically injecting something that you retrieve during the resolve process.

**Comment by robert-bor** [comment]
Ok, clear. Is there some material to read up on the planned resolve functionality? Very interested in the progress of that.

The interface description for canActivate is the following:
```
export interface CanActivate {
    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | boolean;
}
```

I assume state can also be used to set variables on and then read those in the component, correct? That would pretty much solve my issue for now.

**Comment by nosachamos** [comment]
Any advantage of fetching that data in the guard, instead of within the
component itself? I can't think of any.

2016-06-16 14:17 GMT-05:00 Robert Bor <notifications@github.com>:

**Comment by brandonroberts** [comment]
@nosachamos Only if you want to ensure the data is completely loaded before rendering. 

@robert-bor there are blog posts coming in the future describing such functionality. The RouterState is immutable so trying to modify it isn't going to achieve what you want.

**Comment by robert-bor** [comment]
@nosachamos 

> Any advantage of fetching that data in the guard, instead of within the
component itself? I can't think of any.

The reason I want to do it this way is to prevent having to create logic to deal with a product not yet loaded. Having a system in a predictable state makes it less error-prone and easier to reason about.

Of course we can have a discussion on how useful that is and I will gladly oblige. It might also be useful to verify the validity of having a `resolve` by reading this (old) discussion by people I hold in high esteem: https://github.com/angular/router/issues/100

@brandonroberts 

> there are blog posts coming in the future describing such functionality. The RouterState is immutable so trying to modify it isn't going to achieve what you want.

Blocked there then. I will have to go along with your solution of having a single-purpose service catering as a value holder. Not my favourite solution as you can imagine :) I will keep a close eye on the blog posts.


Thanks a lot, both of you, for answering my questions!
