### ISSUE TITLE
 Incompatibility  with bootstrap's 3.0 navbar

### ISSUE THREAD

**Issue by mi9rom** [angular/vladivostok#69]
@angular/router@3.0.0-alpha.6

Simplified code: 
`<nav class="navbar navbar-default ">
        <a [routerLink]="['/about']">THIS WORKS </a>
        <ul class="nav navbar-nav">
            <li><a [routerLink]="['/about']"  data-target=".whateverHere">THIS DOES NOT WORK </a></li>
        </ul>
    </nav>
`

Removing the data-target directive fixes the problem, but unfortunately I need this directive.

**Comment by brandonroberts** [comment]
@mi9rom This isn't a router issue. In order to use the `data-target` you need to use an attribute binding.

```html
<a [routerLink]="['/about']" [attr.data-target]="'.whateverHere'">
```

**Comment by mi9rom** [comment]
@brandonroberts   Your solution works, thank you. There was no problem when using   @angular/router@2.0.0-RC2.
