### ISSUE TITLE
queryParams in routerLink

### ISSUE THREAD

**Issue by thomasgros** [angular/vladivostok#77]
For some reason I can't manage to use queryParams with the [routerLink] directive, is it even possible ?

I've tried things like [routerLink]="['../', {queryParams: {page: page - 1}}]  but without any success.

**Comment by otodockal** [comment]
yes

```
<a [routerLink]="['../']" [queryParams]="{page: page - 1}">page</a>
```

**Comment by thomasgros** [comment]
It works perfectly, thank you !
