### ISSUE TITLE
ActivatedRoute.params vs NavigationExtras.queryParams

### ISSUE THREAD

**Issue by briananderson1222** [angular/vladivostok#78]
Are there alternate ways to access ?& query parameters? Is one deprecated in favor of the other? 

When using the router to navigate with NavigationExtras.queryParameters the url is getting appended with the ?& syntax. I have not yet seen any way of accessing these query parameters as I am currently using the ActivatedRoute.params Observables to get parameter information. 

Is there any current way of navigating using the ; query parameter syntax as this seems to be what currently works?

Any information here would be great

**Comment by briananderson1222** [comment]
Is there any way of navigating using the ; param syntax?

**Comment by brandonroberts** [comment]
Yes, you provide an object for matrix params.

```js
router.navigate(['/route/path', { id: value }]); // navigate to /route/path;id=value
```
