### ISSUE TITLE
default route (index: true) then link does not have expected behavior

### ISSUE THREAD

**Issue by foxjazz** [angular/vladivostok#82]
When the app comes up, the correct route page is displayed i.e. Regions.
Then when moving off the page to other pages, and the revisiting regions the link does nothing.
I don't think this is expected behavior. Or I could be configured incorrectly.

Below is the code that is used in discovery phase.

my component:
` <nav>
        <a [routerLink]="['/help']">Help</a>
        <a [routerLink]="['/regions']">Region</a>
        <a [routerLink]="['/items']">Items by groups</a>
        <a [routerLink]="['/priceboard']">Price Board</a>
        <a [routerLink]="['/ibg']"> (under construction) Price Chart</a>
    </nav>
    `<router-outlet></router-outlet>``

const routes: RouterConfig = [ { 
  path: '/help', component: HelpComponent },
  { path: '/regions', component: RegionComponent, index: true },
  { path: '/items', component: ibgComponent },
  { path: '/priceboard', component: PriceBoardComponent },
  { path: '/ibg', component: ibgComponent }
];

**Comment by DzmitryShylovich** [comment]
`index: true` was deprecated. use `""` path and redirect instead.

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9491
