### ISSUE TITLE
default route with redirectTo not working

### ISSUE THREAD

**Issue by xmlking** [angular/vladivostok#85]
First time when access root URL ("/") it redirects to  crisis-center as expected.
But when I click one of the crisis list items, I am getting attached error.
if I go to Heroes link and come back to CrisisCenter, it works as expected.
any suggestion to fix it ? 

```ts
export const CrisisCenterRoutes: RouterConfig = [
  { path: '', redirectTo: 'crisis-center', terminal: true},
  {
    path: 'crisis-center',
    component: CrisisCenterComponent,
    children: [
      {
        path: 'admin',
        component: CrisisAdminComponent,
        canActivate: [AuthGuard]
      },
      {
        path: ':id',
        component: CrisisDetailComponent,
        canDeactivate: [CanDeactivateGuard]
      },
      { path: '',
        component: CrisisListComponent
      }
    ]
  }
];
```
![image](https://cloud.githubusercontent.com/assets/627951/16178918/90d1be20-360a-11e6-915b-85ff892808b4.png)

**Comment by t246246** [comment]
I'm not sure if it is a spec, but
```javascript
{path: '', redirectTo: '/crisis-center', terminal: true}
```
is working on alpha-7.

**Comment by xmlking** [comment]
router 3.0.0 alpha.7 deprecated usage of "/"

**Comment by t246246** [comment]
I know but it is for 'path'. Not mentioned to 'redirectTo'.

**Comment by xmlking** [comment]
Thanks @t246246 
changing  `{ path: '', redirectTo: 'crisis-center', terminal: true}` to  `{ path: '', redirectTo: '/crisis-center', terminal: true}` worked as expected.

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9493
