### ISSUE TITLE
routerLink directive on Root App Component template doesn't persist queryParams

### ISSUE THREAD

**Issue by briananderson1222** [angular/vladivostok#88]
In the template I have for my root app component I use the routerLink directive to direct a user back to the 'home' of my app throughout the application. This is not the only place I use a routerLink back to the home page but I have noticed that this is the only link that doesn't include seem to persist my queryParams when navigating around the application. 

Load URL appending `/route?test=test`

app.component.html
```js
<a [routerLink]="['/home']">{{ 'HOME' | translate }}</a>
```
--> This navigates to /home

some.component.html
```js
<a [routerLink]="['/home']">{{ 'HOME' | translate }}</a>
```
--> This navigates to /home?test=test

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9495
