### ISSUE TITLE
router-outlet on child route inside of conditional can't be found

### ISSUE THREAD

**Issue by mattem** [angular/vladivostok#92]
When the `router-outlet` directive is inside a conditional (for example, `<div *ngIf="someExpression">`) on a child route, the router fails to find the primary outlet, causing the following error: 

> Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'CrisisListComponent'

Here is a [plunkr](http://plnkr.co/edit/4P67k6REnHQKIA3D2ae3) showing the issue.

The AppComponent contains an outlet inside a conditional, but this is found and used correctly, but the outlet on the CrisisCenterComponent is not found.

Is this the expected behavior?

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9500
