### ISSUE TITLE
404 - Extra slash in import /router//bundles/router.umd.js

### ISSUE THREAD

**Issue by sethdorris** [angular/vladivostok#93]
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
404 Error http://localhost:3000/node_modules/@angular/router//bundles/router.umd.js 

Angular seems to be adding an extra / after router and before bundles folder

**Expected/desired behavior**

I expect the path to be only one slash

**Reproduction of the problem**
https://github.com/sethdorris/practice_angular2

just clone my github repo and "npm start"

**What is the expected behavior?**
The error does not occur when you remove the bootstrapping of the application with APP_ROUTER_PROVIDERS

**What is the motivation / use case for changing the behavior?**
I am trying to use Angular Router

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
* **Angular Router Version.** 3.0.0-alpha.7
 
* **Browser:** Chrome 51.0.2704.103 m (64-bit) 
 
* **Language:**  TypeScript 1.8.10

**Comment by brandonroberts** [comment]
This is an issue with your SystemJS config: https://github.com/sethdorris/practice_angular2/blob/master/systemjs.config.js#L36

Removed the `/` before `bundles`
