### ISSUE TITLE
Cannot Find Routes, and Router Issues but Routing works?

### ISSUE THREAD

**Issue by sethdorris** [angular/vladivostok#94]
So I have a repo here -- https://github.com/sethdorris/practice_angular2

Everything works great with Angular Router and Route handling when you run the application, however, I am getting the following errors in the console. 

![2016-06-20_15-57-29](https://cloud.githubusercontent.com/assets/12013667/16211635/f31e8914-36ff-11e6-8943-b99c650ce439.jpg)

**Comment by DzmitryShylovich** [comment]
add `{path: '', redirectTo: 'welcome', terminal: true}`

**Comment by sethdorris** [comment]
takes care of everything except the Uncaught Type error for cannot read property 'component' of undefined.

**Comment by briananderson1222** [comment]
@sethdorris can you provide a plunker? That error seems unrelated to the router in fact have you looked at line 106 in your description.ts file? I don't see that file in your repo.

**Comment by sethdorris** [comment]
@briananderson1222 that's output from some dependency... I did not write description.ts

**Comment by briananderson1222** [comment]
Need a more minimal example. I've never come across a description.ts file

**Comment by sethdorris** [comment]
I don't even know where to begin to start at minifying my example ,because I do not know what or where description.ts is...

**Comment by sethdorris** [comment]
![2016-06-20_15-57-29](https://cloud.githubusercontent.com/assets/12013667/16212036/6d1e09fe-3702-11e6-9059-4299b8c02156.jpg)

**Comment by nosachamos** [comment]
This is usually caused by the router not finding your component.

2016-06-20 17:17 GMT-05:00 Seth Dorris <notifications@github.com>:

**Comment by sethdorris** [comment]
@nosachamos right... which would make sense if the routing did not work in my application.. but everything works, just getting the error logged.. which is why I don't understand what is happening.

**Comment by briananderson1222** [comment]
Just pulled down the repo, made the fix suggested above by @DzmitryShylovich and I don't see this issue. Can you make sure you clean your npm dependencies and try again.

**Comment by sethdorris** [comment]
@briananderson1222 cleaning the dependencies resolved the issue. 

Thanks all.
